/// Server core abstraction layer.
///
/// Provides abstract interfaces for media server communication,
/// supporting multiple backends (Jellyfin, Emby).
library;

export 'src/media_server_client.dart';
export 'src/models/server_type.dart';
export 'src/models/device_info.dart';
export 'src/models/enums.dart';
export 'src/models/server_models.dart';
export 'src/models/playback_models.dart';
export 'src/models/system_models.dart';
export 'src/models/user_policy.dart';
export 'src/models/websocket_models.dart';
export 'src/models/syncplay_models.dart';
export 'src/models/query_filter_models.dart';
export 'src/api/auth_api.dart';
export 'src/api/syncplay_api.dart';
export 'src/api/item_fields.dart';
export 'src/api/items_api.dart';
export 'src/api/playback_api.dart';
export 'src/api/image_api.dart';
export 'src/api/trickplay_api.dart';
export 'src/api/session_api.dart';
export 'src/api/system_api.dart';
export 'src/api/user_library_api.dart';
export 'src/api/user_views_api.dart';
export 'src/api/live_tv_api.dart';
export 'src/api/instant_mix_api.dart';
export 'src/api/display_preferences_api.dart';
export 'src/api/users_api.dart';
export 'src/api/admin_system_api.dart';
export 'src/api/admin_users_api.dart';
export 'src/api/admin_library_api.dart';
export 'src/api/admin_environment_api.dart';
export 'src/api/admin_tasks_api.dart';
export 'src/api/admin_plugins_api.dart';
export 'src/api/admin_devices_api.dart';
export 'src/api/admin_api_keys_api.dart';
export 'src/api/admin_backup_api.dart';
export 'src/api/admin_live_tv_api.dart';
export 'src/api/admin_items_api.dart';
export 'src/api/client_log_api.dart';
export 'src/models/admin_models.dart';
export 'src/models/device_models.dart';
export 'src/models/plugin_models.dart';
export 'src/api/games_api.dart';
export 'src/api/moonbase_games_api.dart';
export 'src/models/games_models.dart';
export 'src/feature/feature_detector.dart';
export 'src/diagnostics/server_log_sink.dart';
export 'src/diagnostics/performance_trace.dart';
export 'src/diagnostics/performance_interceptor.dart';
export 'src/network/configure_server_dio.dart';
export 'src/network/server_user_agent.dart';
export 'src/network/auth_header.dart';
export 'src/network/redirect_interceptor.dart';
export 'src/network/server_probe.dart';
export 'src/network/query_filters_reader.dart';
